@host = https://localhost:7176

###
GET {{host}}/weatherforecast HTTP/1.1
content-type: application/json

### 
# @name loginRequest
POST {{host}}/security/getToken HTTP/1.1
content-type: application/json

{
    "username": "admin@test.com",
    "password": "Pass"
}

###
@token = {{loginRequest.response.body.$}}

###
GET {{host}}/secret HTTP/1.1
Authorization: Bearer {{token}}


###admins seacret
GET {{host}}/admin HTTP/1.1
Authorization: Bearer {{token}}

###
//should return 403 - user dont have admin2 role
GET {{host}}/admin2 HTTP/1.1
Authorization: Bearer {{token}}